spring:
  application:
    name: "Spring-HW-6"


  # H2 database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb         # будем использовать БД в памяти.
    username: sa
    password:
  # консоль для отладки
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true      # для удаленного доступа

  # автозапуск schema.sql
  sql:
    init:
      mode: always
  # Spring Jpa Hibernate
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

    generate-ddl: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # swagger
  springdoc:
    show-actuator: false
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
